packages:
  - packages/*

catalog:
  '@babel/core': ^7.27.1
  '@best-shot/cli': ^0.18.4
  '@best-shot/core': ^0.12.17
  '@best-shot/dev-server': ^0.20.2
  '@best-shot/preset-asset': ^0.14.1
  '@best-shot/preset-babel': ^0.17.8
  '@best-shot/preset-react': ^0.17.5
  '@best-shot/preset-style': ^0.15.5
  '@best-shot/preset-web': ^0.17.3
  '@nice-move/cli': ^0.11.25
  '@nice-move/eslint-config-base': ^0.12.21
  '@nice-move/eslint-config-react': ^0.12.21
  '@nice-move/eslint-config-vue': ^0.12.21
  '@nice-move/prettier-config': ^0.14.15
  '@nice-move/stylelint-config': ^0.10.16
  '@nice-move/tsconfig': ^0.2.10
  cheetor: ^0.13.0
  core-js: ^3.42.0
  eslint: ^9.27.0
  garou: '>=0.9.8'
  prettier: ^3.5.3
  react-dom: ^18.3.1
  react: ^18.3.1
  stylelint: ^16.19.1
  typescript: ~5.8.3
  vue: ~3.5.14
  webpack: ^5.99.9

overrides:
  eslint: ^9.27.0
  eslint-plugin-react-hooks: ^5.2.0
