packages:
  - packages/*

catalog:
  '@babel/core': ^8.0.1
  '@best-shot/cli': ^0.20.0
  '@best-shot/core': ^0.14.0
  '@best-shot/dev-server': ^0.22.0
  '@best-shot/preset-asset': ^0.16.0
  '@best-shot/preset-babel': ^0.19.0
  '@best-shot/preset-mini': ^0.12.0
  '@best-shot/preset-react': ^0.19.0
  '@best-shot/preset-style': ^0.17.0
  '@best-shot/preset-vue': ^0.17.0
  '@best-shot/preset-web': ^0.19.0
  '@nice-move/cli': ^0.11.32
  '@nice-move/eslint-config-base': ^0.15.3
  '@nice-move/eslint-config-react': ^0.15.3
  '@nice-move/eslint-config-vue': ^0.15.3
  '@nice-move/prettier-config': ^0.15.8
  '@nice-move/stylelint-config': ^0.10.29
  '@nice-move/tsconfig': ^0.5.0
  cheetor: ^0.13.0
  core-js: ^3.49.0
  eslint: ^9.39.4
  garou: '>=0.9.21'
  prettier: ~3.8.4
  react: '>=18.3.1'
  react-dom: '>=18.3.1'
  stylelint: ^17.13.0
  typescript: ~6.0.3
  vue: ~3.5.38
  webpack: ^5.107.2

configDependencies:
  pnpm-plugin-nice-move: 0.3.5+sha512-GCIOMaitJFiSwi3diByPwKitZHgssXMS0QtyMz5zdr/2MuLymwUve00OEwd1ZvyentUTBzL98v5kyLfQ4ZuXUQ==

minimumReleaseAgeExclude:
  - postcss-preset-evergreen
  - babel-preset-evergreen
  - browserslist

overrides:
  eslint: 'catalog:'
  eslint-plugin-react-hooks: ^5.2.0
  sass: '-'

trustPolicyExclude:
  - miniprogram-api-typings
  - semver
