packages:
  - packages/*

catalog:
  '@babel/core': ^7.28.5
  '@best-shot/cli': ^0.19.3
  '@best-shot/core': ^0.13.8
  '@best-shot/dev-server': ^0.21.2
  '@best-shot/preset-asset': ^0.15.2
  '@best-shot/preset-babel': ^0.18.6
  '@best-shot/preset-mini': ^0.11.8
  '@best-shot/preset-react': ^0.18.3
  '@best-shot/preset-style': ^0.16.1
  '@best-shot/preset-vue': ^0.16.1
  '@best-shot/preset-web': ^0.18.1
  '@nice-move/cli': ^0.11.27
  '@nice-move/eslint-config-base': ^0.13.11
  '@nice-move/eslint-config-react': ^0.13.11
  '@nice-move/eslint-config-vue': ^0.13.11
  '@nice-move/prettier-config': ^0.15.6
  '@nice-move/stylelint-config': ^0.10.23
  '@nice-move/tsconfig': ^0.3.12
  cheetor: ^0.13.0
  core-js: ^3.47.0
  eslint: ^9.39.1
  garou: ^0.9.16
  prettier: ^3.6.2
  react: ^18.3.1
  react-dom: ^18.3.1
  stylelint: ^16.26.0
  typescript: ~5.9.3
  vue: ~3.5.25
  webpack: ^5.103.0

overrides:
  eslint: 'catalog:'
  eslint-plugin-react-hooks: ^5.2.0

updateConfig:
  ignoreDependencies:
    - react
    - react-dom
