packages:
  - packages/*

catalog:
  '@babel/core': ^7.28.0
  '@best-shot/cli': ^0.19.1
  '@best-shot/core': ^0.13.0
  '@best-shot/dev-server': ^0.21.0
  '@best-shot/preset-asset': ^0.15.1
  '@best-shot/preset-babel': ^0.18.2
  '@best-shot/preset-mini': ^0.11.3
  '@best-shot/preset-react': ^0.18.1
  '@best-shot/preset-style': ^0.16.0
  '@best-shot/preset-vue': ^0.16.0
  '@best-shot/preset-web': ^0.18.0
  '@nice-move/cli': ^0.11.26
  '@nice-move/eslint-config-react': ^0.12.25
  '@nice-move/eslint-config-base': ^0.12.25
  '@nice-move/eslint-config-vue': ^0.12.25
  '@nice-move/prettier-config': ^0.14.15
  '@nice-move/stylelint-config': ^0.10.20
  '@nice-move/tsconfig': ^0.2.14
  cheetor: ^0.13.0
  core-js: ^3.44.0
  eslint: ^9.30.1
  garou: ^0.9.11
  prettier: ^3.6.2
  react-dom: ^18.3.1
  react: ^18.3.1
  stylelint: ^16.21.1
  typescript: ~5.8.3
  vue: ~3.5.17
  webpack: ^5.100.0

overrides:
  eslint: ^9.30.1
  eslint-plugin-react-hooks: ^5.2.0

updateConfig:
  ignoreDependencies:
    - react
    - react-dom
