packages:
  - packages/*

catalog:
  '@babel/core': ^7.29.0
  '@best-shot/cli': ^0.19.3
  '@best-shot/core': ^0.13.14
  '@best-shot/dev-server': ^0.21.5
  '@best-shot/preset-asset': ^0.15.4
  '@best-shot/preset-babel': ^0.18.7
  '@best-shot/preset-mini': ^0.11.26
  '@best-shot/preset-react': ^0.18.4
  '@best-shot/preset-style': ^0.16.5
  '@best-shot/preset-vue': ^0.16.4
  '@best-shot/preset-web': ^0.18.3
  '@nice-move/cli': ^0.11.31
  '@nice-move/eslint-config-base': ^0.14.2
  '@nice-move/eslint-config-react': ^0.14.2
  '@nice-move/eslint-config-vue': ^0.14.2
  '@nice-move/prettier-config': ^0.15.8
  '@nice-move/stylelint-config': ^0.10.25
  '@nice-move/tsconfig': ^0.4.2
  cheetor: ^0.13.0
  core-js: ^3.48.0
  eslint: ^9.39.4
  garou: ^0.9.17
  prettier: ^3.8.1
  react: ^18.3.1
  react-dom: ^18.3.1
  stylelint: ^16.26.1
  typescript: ~5.9.3
  vue: ~3.5.30
  webpack: ^5.105.4

configDependencies:
  pnpm-plugin-nice-move: 0.3.1+sha512-pIq4uYqy3pZFCcyuJeGSmhNr3u1MGfNZbjnVKtJWUfM/NfhEBzAvlkHmVG5WYhbqNQA3xuqqaJaiOUGIQvo3JA==

overrides:
  eslint: 'catalog:'
  eslint-plugin-react-hooks: ^5.2.0
  sass: '-'
